excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length: 150
file_length: 500
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
cyclomatic_complexity:
  - 20
